vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    mappings:
        profile_images:
            uri_prefix: /uploads/images/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/images/profiles'
            # allowed_mime_types: ['image/jpeg', 'image/png', 'image/gif', 'image/jpg']
